// <auto-generated />
using System;
using EventEaseLocal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventEaseLocal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604073438_AddEventType")]
    partial class AddEventType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventEaseLocal.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("EventId");

                    b.HasIndex("VenueId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            BookedBy = "Thandi Mokoena",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            EventDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            VenueId = 1
                        },
                        new
                        {
                            BookingId = 2,
                            BookedBy = "Sipho Dlamini",
                            EndTime = new TimeSpan(0, 23, 0, 0, 0),
                            EventDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            VenueId = 2
                        },
                        new
                        {
                            BookingId = 3,
                            BookedBy = "Zephyr Corp Events Team",
                            EndTime = new TimeSpan(0, 23, 30, 0, 0),
                            EventDate = new DateTime(2026, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 3,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            VenueId = 6
                        },
                        new
                        {
                            BookingId = 4,
                            BookedBy = "Sunshine Charity",
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            EventDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 4,
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            VenueId = 3
                        },
                        new
                        {
                            BookingId = 5,
                            BookedBy = "Nova Marketing",
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            EventDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 5,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            VenueId = 7
                        },
                        new
                        {
                            BookingId = 6,
                            BookedBy = "Priya Naidoo",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            EventDate = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 6,
                            StartTime = new TimeSpan(0, 17, 0, 0, 0),
                            VenueId = 4
                        },
                        new
                        {
                            BookingId = 7,
                            BookedBy = "Apex Solutions HR",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            EventDate = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 7,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            VenueId = 5
                        },
                        new
                        {
                            BookingId = 8,
                            BookedBy = "Live Beats Productions",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            EventDate = new DateTime(2026, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 8,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0),
                            VenueId = 1
                        });
                });

            modelBuilder.Entity("EventEaseLocal.Models.BookingDetailsView", b =>
                {
                    b.Property<string>("BookedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("VenueCapacity")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<string>("VenueImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VenueLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_BookingDetails", (string)null);
                });

            modelBuilder.Entity("EventEaseLocal.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Description = "A premier technology conference featuring industry leaders.",
                            EventName = "Annual Tech Conference",
                            EventTypeId = 1,
                            VenueId = 1
                        },
                        new
                        {
                            EventId = 2,
                            Description = "Private wedding reception for the Mokoena family.",
                            EventName = "Wedding Reception - Mokoena",
                            EventTypeId = 2,
                            VenueId = 2
                        },
                        new
                        {
                            EventId = 3,
                            Description = "Formal dinner and awards ceremony for Zephyr Corp employees.",
                            EventName = "Corporate Year-End Gala",
                            EventTypeId = 3,
                            VenueId = 6
                        },
                        new
                        {
                            EventId = 4,
                            Description = "Kickoff event for the annual Sunshine Charity 10K.",
                            EventName = "Charity Fun Run Launch",
                            EventTypeId = 6,
                            VenueId = 3
                        },
                        new
                        {
                            EventId = 5,
                            Description = "Exclusive launch event for the new Nova smartphone line.",
                            EventName = "Product Launch - Nova Phone",
                            EventTypeId = 3,
                            VenueId = 7
                        },
                        new
                        {
                            EventId = 6,
                            Description = "50th birthday celebration for the Naidoo family.",
                            EventName = "Birthday Celebration - Naidoo",
                            EventTypeId = 5,
                            VenueId = 4
                        },
                        new
                        {
                            EventId = 7,
                            Description = "Two-day team building workshop for Apex Solutions.",
                            EventName = "Team Building Retreat",
                            EventTypeId = 7,
                            VenueId = 5
                        },
                        new
                        {
                            EventId = 8,
                            Description = "Live music performances across multiple stages.",
                            EventName = "Music Festival Day Pass",
                            EventTypeId = 4,
                            VenueId = 1
                        });
                });

            modelBuilder.Entity("EventEaseLocal.Models.EventType", b =>
                {
                    b.Property<int>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("EventTypeId");

                    b.ToTable("EventTypes");

                    b.HasData(
                        new
                        {
                            EventTypeId = 1,
                            Name = "Conference"
                        },
                        new
                        {
                            EventTypeId = 2,
                            Name = "Wedding"
                        },
                        new
                        {
                            EventTypeId = 3,
                            Name = "Corporate"
                        },
                        new
                        {
                            EventTypeId = 4,
                            Name = "Concert / Festival"
                        },
                        new
                        {
                            EventTypeId = 5,
                            Name = "Birthday / Private"
                        },
                        new
                        {
                            EventTypeId = 6,
                            Name = "Charity"
                        },
                        new
                        {
                            EventTypeId = 7,
                            Name = "Workshop"
                        },
                        new
                        {
                            EventTypeId = 8,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("EventEaseLocal.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VenueId");

                    b.HasIndex("VenueName")
                        .IsUnique();

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Capacity = 500,
                            ImageUrl = "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600",
                            Location = "123 Main Street, Johannesburg",
                            VenueName = "Grand Ballroom"
                        },
                        new
                        {
                            VenueId = 2,
                            Capacity = 200,
                            ImageUrl = "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=600",
                            Location = "45 Rivonia Road, Sandton",
                            VenueName = "Skyline Terrace"
                        },
                        new
                        {
                            VenueId = 3,
                            Capacity = 150,
                            ImageUrl = "https://images.unsplash.com/photo-1510076857177-7470076d4098?w=600",
                            Location = "78 Oak Avenue, Pretoria",
                            VenueName = "The Garden Pavilion"
                        },
                        new
                        {
                            VenueId = 4,
                            Capacity = 300,
                            ImageUrl = "https://images.unsplash.com/photo-1544928147-79a2dbc1f389?w=600",
                            Location = "12 Beach Road, Durban",
                            VenueName = "Ocean View Hall"
                        },
                        new
                        {
                            VenueId = 5,
                            Capacity = 80,
                            ImageUrl = "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=600",
                            Location = "5 Peak Drive, Drakensberg",
                            VenueName = "Mountain Lodge"
                        },
                        new
                        {
                            VenueId = 6,
                            Capacity = 250,
                            ImageUrl = "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=600",
                            Location = "90 Wine Route, Stellenbosch",
                            VenueName = "The Vineyard Estate"
                        },
                        new
                        {
                            VenueId = 7,
                            Capacity = 1000,
                            ImageUrl = "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600",
                            Location = "200 Commissioner Street, Johannesburg",
                            VenueName = "City Conference Centre"
                        });
                });

            modelBuilder.Entity("EventEaseLocal.Models.Booking", b =>
                {
                    b.HasOne("EventEaseLocal.Models.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventEaseLocal.Models.Venue", "Venue")
                        .WithMany("Bookings")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventEaseLocal.Models.Event", b =>
                {
                    b.HasOne("EventEaseLocal.Models.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventEaseLocal.Models.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventEaseLocal.Models.Event", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("EventEaseLocal.Models.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventEaseLocal.Models.Venue", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
